/*
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeName;
import lombok.Data;

import java.math.BigDecimal;

@JsonTypeName("SendBird.MessageResponseV1")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-08-31T16:21:40.271053+01:00[Europe/London]")
@JsonIgnoreProperties(ignoreUnknown = true)
@Data
public class SendBirdMessageResponseV1 {
    /**
     *
     */
    private BotMessageDetail message;

    @Data
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class BotMessageDetail {
        /**
         * Type
         */
        private String type;

        /**
         * MessageId
         */
        @JsonProperty("message_id")
        private BigDecimal messageId;

        /**
         * CustomType
         */
        @JsonProperty("custom_type")
        private String customType;

        /**
         * Data
         */
        private String data;

        /**
         * CreatedAt
         */
        @JsonProperty("created_at")
        private BigDecimal createdAt;

        /**
         * UpdatedAt
         */
        @JsonProperty("updated_at")
        private BigDecimal updatedAt;

        /**
         * User
         */
        private MessageUserDetail user;

        /**
         * MentionType
         */
        @JsonProperty("mention_type")
        private String mentionType;

        /**
         * ChannelUrl
         */
        @JsonProperty("channel_url")
        private String channelUrl;

        /**
         * ChannelType
         */
        @JsonProperty("channel_type")
        private String channelType;
    }

    @Data
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class MessageUserDetail {
        /**
         * UserId
         */
        @JsonProperty("user_id")
        private String userId;

        /**
         * Nickname
         */
        @JsonProperty("nickename")
        private String nikename;

        /**
         * IsActive
         */
        @JsonProperty("is_active")
        private Boolean isActive;
    }
}

